CREATE DATABASE affairs_order
DEFAULT CHARACTER SET utf8
DEFAULT COLLATE utf8_general_ci;

USE affairs_order;

CREATE TABLE users 
(
	id_user INT AUTO_INCREMENT PRIMARY KEY,
	dt_add TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	email VARCHAR(128) NOT NULL UNIQUE,
	name VARCHAR(128) NOT NULL,
	password VARCHAR(64) NOT NULL

);

CREATE TABLE projects 
(
	project_id INT AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(68) UNIQUE,
	id_user INT,
	FOREIGN KEY (id_user) REFERENCES users(id_user)
);

CREATE TABLE tasks
(
	id_task INT AUTO_INCREMENT PRIMARY KEY,
	dt_add TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	status TINYINT DEFAULT 0,
	name VARCHAR(68) NOT NULL,
	file VARCHAR(100),
	term TIMESTAMP,
	project_id INT,
	FOREIGN KEY (project_id) REFERENCES projects(project_id)
);
mysqlmysql